name: toggles for regions

on:

  push:

  workflow_dispatch:
    inputs:
      deploy_oregon:
        description: 'Deploy to Oregon'
        default: true
        required: true
        type: boolean
      deploy_sydney:
        description: 'Deploy to Sydney'
        default: true
        required: true
        type: boolean

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - run: echo "deploy_oregon=${{ inputs.deploy_oregon }}, deploy_sydney=${{ inputs.deploy_sydney }}"

  deploy_to_oregon:
    if: toJson(inputs.deploy_oregon) != 'false'
    runs-on: ubuntu-latest
    steps:
      - run: echo "deploy_oregon=${{ inputs.deploy_oregon }}, deploy_sydney=${{ inputs.deploy_sydney }}"

  deploy_to_sydney:
    if: toJson(inputs.deploy_sydney) != 'false'
    runs-on: ubuntu-latest
    steps:
      - run: echo "deploy_oregon=${{ inputs.deploy_oregon }}, deploy_sydney=${{ inputs.deploy_sydney }}"

